# Generated by Django 6.0.6 on 2026-06-28 04:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Success', 'Success'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20)),
                ('trigger', models.CharField(blank=True, default='', max_length=100)),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('queue_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentic_analysis_jobs', to='cases.case')),
            ],
            options={
                'db_table': 'agentic_case_analysis_jobs',
                'ordering': ['scheduled_at', 'created_at'],
            },
        ),
    ]
