# Generated by Django 6.0.7 on 2026-08-17 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic', '0001_initial'),
        ('cases', '0004_caserelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmCallRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=50)),
                ('prompt_hash', models.CharField(blank=True, default='', max_length=64)),
                ('provider_name', models.CharField(blank=True, default='', max_length=100)),
                ('model_name', models.CharField(blank=True, default='', max_length=200)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('tokens_in', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_out', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('trimmed_tiers', models.JSONField(blank=True, default=list)),
                ('raw_response', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(blank=True, default='', max_length=100)),
                ('source_id', models.CharField(blank=True, default='', max_length=64)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_call_records', to='cases.case')),
            ],
            options={
                'db_table': 'agentic_llm_call_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
