# Generated by Django 6.0.7 on 2026-08-17 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic', '0002_llmcallrecord'),
        ('cases', '0004_caserelationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageSuppression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_type', models.CharField(choices=[('rule', 'Rule name'), ('entity', 'Artifact value'), ('subnet', 'IP subnet'), ('user', 'Username')], db_index=True, max_length=20)),
                ('pattern', models.CharField(max_length=500)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(help_text='Mandatory. A suppression without an end date is not allowed.')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_suppressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agentic_triage_suppressions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verdict', models.CharField(choices=[('true_positive', 'True Positive'), ('false_positive', 'False Positive'), ('benign_true_positive', 'Benign True Positive'), ('needs_more_info', 'Needs More Info')], db_index=True, max_length=30)),
                ('false_positive_class', models.CharField(blank=True, choices=[('suppressed', 'Already suppressed'), ('verified_legitimate', 'Verified legitimate activity'), ('rule_misconfiguration', 'Rule misconfiguration'), ('other', 'Other')], default='', max_length=30)),
                ('severity_ai', models.CharField(blank=True, default='', max_length=20)),
                ('impact_ai', models.CharField(blank=True, default='', max_length=20)),
                ('priority_ai', models.CharField(blank=True, default='', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('needs_human', models.BooleanField(db_index=True, default=False)),
                ('mitre_tactics', models.JSONField(blank=True, default=list)),
                ('mitre_techniques', models.JSONField(blank=True, default=list)),
                ('kill_chain_phase', models.CharField(blank=True, default='', max_length=100)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('reasoning_vi', models.TextField(blank=True, default='')),
                ('reasoning_en', models.TextField(blank=True, default='')),
                ('prompt_family', models.CharField(blank=True, default='', max_length=50)),
                ('context_tiers', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('human_verdict', models.CharField(blank=True, choices=[('true_positive', 'True Positive'), ('false_positive', 'False Positive'), ('benign_true_positive', 'Benign True Positive'), ('needs_more_info', 'Needs More Info')], default='', max_length=30)),
                ('human_verdict_at', models.DateTimeField(blank=True, null=True)),
                ('human_verdict_note', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_results', to='cases.case')),
                ('human_verdict_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_overrides', to=settings.AUTH_USER_MODEL)),
                ('llm_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_results', to='agentic.llmcallrecord')),
                ('suppressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_results', to='agentic.triagesuppression')),
            ],
            options={
                'db_table': 'agentic_triage_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', '-created_at'], name='triage_case_created_idx')],
            },
        ),
    ]
