# Generated by Django 6.0.7 on 2026-08-17 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic', '0003_triagesuppression_triageresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='IocVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator_type', models.CharField(db_index=True, max_length=20)),
                ('indicator_value', models.CharField(db_index=True, max_length=1000)),
                ('verdict', models.CharField(choices=[('malicious', 'Malicious'), ('suspicious', 'Suspicious'), ('benign', 'Benign'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_internal', models.BooleanField(default=False)),
                ('first_seen', models.CharField(blank=True, default='', max_length=64)),
                ('last_seen', models.CharField(blank=True, default='', max_length=64)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('associated_actors', models.JSONField(blank=True, default=list)),
                ('associated_campaigns', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('notes_vi', models.TextField(blank=True, default='')),
                ('notes_en', models.TextField(blank=True, default='')),
                ('sources_used', models.JSONField(blank=True, default=list)),
                ('injection_flags', models.JSONField(blank=True, default=list)),
                ('rejected_references', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('llm_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ioc_verifications', to='agentic.llmcallrecord')),
            ],
            options={
                'db_table': 'agentic_ioc_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['verdict', '-created_at'], name='ioc_verdict_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('indicator_type', 'indicator_value'), name='ioc_verification_unique_indicator')],
            },
        ),
    ]
