# Generated by Django 6.0.7 on 2026-08-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic', '0004_iocverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageresult',
            name='asset_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='triageresult',
            name='entities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='triageresult',
            name='facts',
            field=models.JSONField(blank=True, default=dict, help_text='Deterministic facts rendered from database records, never generated by the model.'),
        ),
        migrations.AddField(
            model_name='triageresult',
            name='missing_context',
            field=models.JSONField(blank=True, default=list, help_text='Required fields still absent after enrichment, with what was tried and why it failed.'),
        ),
        migrations.AddField(
            model_name='triageresult',
            name='quality_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
