# Generated by Django 6.0.7 on 2026-08-19 11:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentic', '0005_triageresult_asset_context_triageresult_entities_and_more'),
        ('alerts', '0003_alert_alert_event_time_idx'),
        ('cases', '0004_caserelationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntHypothesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement', models.TextField(blank=True, default='')),
                ('mitre_technique', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('rationale', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('refuted', 'Refuted'), ('inconclusive', 'Inconclusive')], db_index=True, default='pending', max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'agentic_hunt_hypotheses',
                'ordering': ['plan', 'position'],
            },
        ),
        migrations.CreateModel(
            name='HuntFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conclusion', models.CharField(choices=[('confirmed', 'Confirmed'), ('refuted', 'Refuted'), ('inconclusive', 'Inconclusive')], db_index=True, default='inconclusive', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=list, help_text='References to real records. Evidence the model only describes is not accepted.')),
                ('llm_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunt_findings', to='agentic.llmcallrecord')),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='agentic.hunthypothesis')),
            ],
            options={
                'db_table': 'agentic_hunt_findings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HuntPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('budget_exhausted', 'Budget Exhausted')], db_index=True, default='pending', max_length=20)),
                ('mode', models.CharField(choices=[('advisory', 'Advisory'), ('auto', 'Auto')], db_index=True, default='advisory', help_text='advisory generates queries without running them. auto executes them read-only behind the SIEM and EDR guards.', max_length=20)),
                ('hypotheses_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, default='', help_text='Why the plan stopped early, for example which budget ceiling was reached.', max_length=500)),
                ('budget_snapshot', models.JSONField(blank=True, default=dict, help_text='Ceilings in force when the plan ran, so a later config change does not rewrite history.')),
                ('error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunt_plans', to=settings.AUTH_USER_MODEL)),
                ('llm_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunt_plans', to='agentic.llmcallrecord')),
            ],
            options={
                'db_table': 'agentic_hunt_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hunthypothesis',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='agentic.huntplan'),
        ),
        migrations.CreateModel(
            name='HuntQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(choices=[('qradar', 'QRadar'), ('trellix', 'Trellix')], db_index=True, max_length=20)),
                ('query_text', models.TextField(blank=True, default='')),
                ('purpose', models.TextField(blank=True, default='')),
                ('expected_evidence', models.TextField(blank=True, default='', help_text='How to read a positive result.')),
                ('negative_interpretation', models.TextField(blank=True, default='', help_text='What an empty result does and does not prove.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected by guard'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sample_rows', models.JSONField(blank=True, default=list)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('guard_rejection_reason', models.TextField(blank=True, default='', help_text='Why the read-only guard refused this query. A rejected query is surfaced, never silently skipped.')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunt_queries', to=settings.AUTH_USER_MODEL)),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='agentic.hunthypothesis')),
            ],
            options={
                'db_table': 'agentic_hunt_queries',
                'ordering': ['hypothesis', 'position'],
            },
        ),
        migrations.CreateModel(
            name='IncidentCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster_id', models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Record ID e.g. cluster_000001', max_length=32, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('primary_entities', models.JSONField(blank=True, default=dict, help_text='Typed entity sets defining this cluster, from triage entity extraction.')),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField(db_index=True)),
                ('link_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('case_count', models.PositiveIntegerField(default=0)),
                ('alert_count', models.PositiveIntegerField(default=0)),
                ('fingerprint', models.CharField(db_index=True, help_text='Hash over the sorted primary entity set. A re-run updates the cluster carrying this fingerprint instead of creating a second one.', max_length=64, unique=True)),
                ('lifecycle_events', models.JSONField(blank=True, default=list, help_text='Append-only merge and split events, so a cluster is never silently replaced.')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='agentic.incidentcluster')),
            ],
            options={
                'db_table': 'agentic_incident_clusters',
                'ordering': ['-window_end', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='huntplan',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_plans', to='agentic.incidentcluster'),
        ),
        migrations.CreateModel(
            name='IncidentClusterMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contribution_score', models.FloatField(default=0.0)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='alerts.alert')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='cases.case')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='agentic.incidentcluster')),
            ],
            options={
                'db_table': 'agentic_incident_cluster_members',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incidentcluster',
            index=models.Index(fields=['status', '-window_end'], name='cluster_status_window_idx'),
        ),
        migrations.AddIndex(
            model_name='huntplan',
            index=models.Index(fields=['cluster', '-created_at'], name='hunt_plan_cluster_idx'),
        ),
        migrations.AddConstraint(
            model_name='incidentclustermember',
            constraint=models.UniqueConstraint(condition=models.Q(('case__isnull', False)), fields=('cluster', 'case'), name='cluster_member_unique_case'),
        ),
        migrations.AddConstraint(
            model_name='incidentclustermember',
            constraint=models.UniqueConstraint(condition=models.Q(('alert__isnull', False)), fields=('cluster', 'alert'), name='cluster_member_unique_alert'),
        ),
    ]
