# Generated by Django 6.0.6 on 2026-07-24 01:20

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cases', '0002_case_case_created_id_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='case',
            index=models.Index(fields=['status', 'severity'], name='case_status_severity_idx'),
        ),
        AddIndexConcurrently(
            model_name='case',
            index=models.Index(fields=['updated_at'], name='case_updated_at_idx'),
        ),
        AddIndexConcurrently(
            model_name='case',
            index=models.Index(fields=['acknowledged_time'], name='case_ack_time_idx'),
        ),
        AddIndexConcurrently(
            model_name='case',
            index=models.Index(fields=['closed_time'], name='case_closed_time_idx'),
        ),
    ]
