# Generated by Django 6.0.7 on 2026-08-17 19:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram')], default='telegram', max_length=20)),
                ('chat_id', models.CharField(help_text='Telegram chat id. Channels look like -1001234567890.', max_length=100)),
                ('message_thread_id', models.CharField(blank=True, default='', help_text='Topic id inside a forum group. Leave empty for a plain chat or channel.', max_length=50)),
                ('language', models.CharField(default='vi', max_length=10)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('min_severity', models.CharField(blank=True, default='', max_length=20)),
                ('min_confidence', models.FloatField(default=0.0)),
                ('verdict_filter', models.JSONField(blank=True, default=list)),
                ('source_filter', models.JSONField(blank=True, default=list)),
                ('min_asset_criticality', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'notification_destinations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('triage.completed', 'Triage completed'), ('triage.needs_human', 'Triage needs human review'), ('discovery.created', 'Attack discovery created'), ('hunt.finding_confirmed', 'Hunt finding confirmed'), ('audit.critical_finding', 'Critical MSSP audit finding'), ('system.worker_unhealthy', 'Worker unhealthy'), ('mssp.sync_failed', 'MSSP sync failed'), ('integration.auth_failed', 'Integration authentication failed')], db_index=True, max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('rendered_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('aggregated_count', models.PositiveIntegerField(default=1)),
                ('dedup_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='notifications.notificationdestination')),
            ],
            options={
                'db_table': 'notification_outbox',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='outbox_status_sched_idx')],
            },
        ),
    ]
