# Generated by Django 6.0.6 on 2026-07-24 01:20

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('alerts', '0003_alert_alert_event_time_idx'),
        ('artifacts', '0002_artifact_artifact_created_id_idx'),
        ('cases', '0003_case_case_status_severity_idx_and_more'),
        ('enrichments', '0002_remove_mcp_provider_choice'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='enrichment',
            index=models.Index(fields=['created_at'], name='enrichment_created_idx'),
        ),
    ]
