# Generated by Django 6.0.6 on 2026-07-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('artifacts', '0002_artifact_artifact_created_id_idx'),
        ('cases', '0002_case_case_created_id_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at', '-id'], name='alert_created_id_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-first_seen_time', '-id'], name='alert_first_seen_id_idx'),
        ),
    ]
