# Generated by Django 6.0.6 on 2026-07-24 01:20

import django.db.models.functions.comparison
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('alerts', '0002_alert_alert_created_id_idx_and_more'),
        ('artifacts', '0002_artifact_artifact_created_id_idx'),
        ('cases', '0003_case_case_status_severity_idx_and_more'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='alert',
            index=models.Index(django.db.models.functions.comparison.Coalesce('last_seen_time', 'first_seen_time', 'created_at'), name='alert_event_time_idx'),
        ),
    ]
