# Generated by Django 6.0.6 on 2026-06-28 04:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playbook_id', models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Record ID e.g. playbook_000001 (记录 ID e.g. playbook_000001)', max_length=32, unique=True)),
                ('name', models.CharField(blank=True, default='', help_text='Executed playbook name (执行剧本名称)', max_length=255)),
                ('user_input', models.TextField(blank=True, default='', help_text='Initial or follow-up user input (初始或后续用户输入)')),
                ('job_status', models.CharField(blank=True, choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending'), ('Running', 'Running')], default='', help_text='Background job status (后台任务状态)', max_length=20)),
                ('job_id', models.CharField(blank=True, default='', help_text='Background job ID (后台任务 ID)', max_length=255)),
                ('remark', models.TextField(blank=True, default='', help_text='Execution remark (执行备注)')),
                ('case', models.ForeignKey(help_text='Trigger source record ID e.g. case_000001(触发源记录 ID e.g. case_0000001)', on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='cases.case')),
                ('user', models.ForeignKey(blank=True, help_text='Playbook requester (剧本请求者)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'playbooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
