# Generated by Django 6.0.6 on 2026-07-24 01:20

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cases', '0003_case_case_status_severity_idx_and_more'),
        ('playbooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='playbook',
            index=models.Index(fields=['created_at', 'job_status'], name='playbook_created_job_idx'),
        ),
    ]
