# Generated by Django 6.0.6 on 2026-07-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['-created_at', '-id'], name='artifact_created_id_idx'),
        ),
    ]
