# Generated by GitHub Copilot on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["-created_at", "-id"], name="audit_time_idx"),
        ),
    ]
