# Generated by Django 6.0.6 on 2026-07-24 01:20

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cases', '0003_case_case_status_severity_idx_and_more'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='knowledge',
            index=models.Index(fields=['created_at', 'source'], name='knowledge_created_src_idx'),
        ),
    ]
