# Generated by Django 6.0.7 on 2026-08-20 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_caserelationship'),
        ('knowledge', '0002_knowledge_knowledge_created_src_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='How much to trust this record. Human-written and human-corrected knowledge outranks anything a model inferred.'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='entities',
            field=models.JSONField(blank=True, default=dict, help_text='Typed entities this record applies to, in the triage extraction shape. Retrieval matches these before it falls back to text.'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Hash over kind and entities. Capturing the same lesson twice updates the existing record instead of adding a duplicate.', max_length=64),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='hit_count',
            field=models.PositiveIntegerField(default=0, help_text='How often this record was retrieved into an investigation, used to rank the useful above the merely recent.'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='kind',
            field=models.CharField(choices=[('false_positive', 'False Positive Context'), ('business_behaviour', 'Business Behaviour'), ('asset_criticality', 'Asset Criticality'), ('identity_criticality', 'Identity Criticality'), ('hunt_finding', 'Hunt Finding'), ('detection_logic', 'Detection Logic'), ('other', 'Other')], db_index=True, default='other', help_text='What this record teaches, which decides how it is retrieved and weighted.', max_length=32),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='last_used_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Case this Knowledge was extracted from; empty for manual Knowledge (知识提取来源 Case, 手动知识为空)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_knowledge', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='source',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Case', 'Case'), ('Triage', 'Triage'), ('HumanOverride', 'Human Override'), ('Hunt', 'Hunt')], default='', help_text='Knowledge source (知识来源)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='knowledge',
            index=models.Index(fields=['kind', '-hit_count'], name='knowledge_kind_hits_idx'),
        ),
    ]
