# Generated by Django 6.0.6 on 2026-06-28 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LdapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('server_uri', models.CharField(blank=True, default='', max_length=500)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('bind_dn', models.CharField(blank=True, default='', max_length=500)),
                ('bind_password', models.TextField(blank=True, default='')),
                ('user_search_base_dn', models.CharField(blank=True, default='', max_length=500)),
                ('user_login_attr', models.CharField(default='uid', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_ldap_config',
            },
        ),
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(max_length=500)),
                ('model', models.CharField(max_length=200)),
                ('api_key', models.TextField(blank=True, default='')),
                ('proxy', models.CharField(blank=True, default='', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_llm_provider_configs',
                'ordering': ['priority', 'name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('prompt_language', models.CharField(default='en', max_length=10)),
                ('stream_maxlen', models.PositiveIntegerField(default=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_runtime_config',
            },
        ),
        migrations.CreateModel(
            name='SiemElkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('host', models.URLField(blank=True, default='', max_length=500)),
                ('api_key', models.TextField(blank=True, default='')),
                ('verify_certs', models.BooleanField(default=False)),
                ('request_timeout_seconds', models.PositiveIntegerField(default=30)),
                ('process_alert_from_index_enabled', models.BooleanField(default=False)),
                ('action_index', models.CharField(blank=True, default='siem-alert', max_length=255)),
                ('action_poll_interval_seconds', models.PositiveIntegerField(default=60)),
                ('action_size', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_siem_elk_config',
            },
        ),
        migrations.CreateModel(
            name='SiemSplunkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.PositiveIntegerField(default=8089)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.TextField(blank=True, default='')),
                ('scheme', models.CharField(default='https', max_length=10)),
                ('verify', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_siem_splunk_config',
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelAlienVaultOTXConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('api_key', models.TextField(blank=True, default='')),
                ('base_url', models.URLField(default='https://otx.alienvault.com/api/v1', max_length=500)),
                ('proxy', models.CharField(blank=True, default='', max_length=500)),
                ('timeout_seconds', models.FloatField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_ti_alienvault_otx_config',
            },
        ),
    ]
