# Generated by Django for OpenCTI threat intelligence settings.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreatIntelOpenCTIConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_id", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("enabled", models.BooleanField(default=False)),
                ("url", models.URLField(default="http://localhost:8080", max_length=500)),
                ("token", models.TextField(blank=True, default="")),
                ("ssl_verify", models.BooleanField(default=False)),
                ("proxy", models.CharField(blank=True, default="", max_length=500)),
                ("timeout_seconds", models.FloatField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "setting_ti_opencti_config",
            },
        ),
    ]
