# Generated by Django 6.0.6 on 2026-07-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_threatintelopencticonfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siemelkconfig',
            name='request_timeout_seconds',
        ),
        migrations.RemoveField(
            model_name='threatintelalienvaultotxconfig',
            name='timeout_seconds',
        ),
        migrations.RemoveField(
            model_name='threatintelopencticonfig',
            name='timeout_seconds',
        ),
    ]
