# Generated by Django 6.0.6 on 2026-07-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_siemelkconfig_request_timeout_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimeconfig',
            name='dashboard_refresh_interval_seconds',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
