# Generated by Django 6.0.7 on 2026-08-01 09:55

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_runtimeconfig_dashboard_refresh_interval_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='Key must start with an uppercase letter and contain only uppercase letters, numbers, and underscores.', regex='^[A-Z][A-Z0-9_]{0,127}$')])),
                ('value', models.TextField()),
                ('is_secret', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_custom_variables',
                'ordering': ['key'],
            },
        ),
    ]
