# Generated by Django 6.0.7 on 2026-08-03

from django.db import migrations, models


def copy_string_values(apps, schema_editor):
    CustomVariable = apps.get_model("settings", "CustomVariable")
    for variable in CustomVariable.objects.only("id", "value").iterator():
        variable.typed_value = variable.value
        variable.save(update_fields=["typed_value"])


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0005_customvariable"),
    ]

    operations = [
        migrations.AddField(
            model_name="customvariable",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("string", "String"),
                    ("integer", "Integer"),
                    ("float", "Float"),
                    ("boolean", "Boolean"),
                    ("list", "List"),
                    ("dictionary", "Dictionary"),
                ],
                default="string",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customvariable",
            name="typed_value",
            field=models.JSONField(null=True),
        ),
        migrations.RunPython(copy_string_values),
        migrations.RemoveField(
            model_name="customvariable",
            name="value",
        ),
        migrations.RenameField(
            model_name="customvariable",
            old_name="typed_value",
            new_name="value",
        ),
        migrations.AlterField(
            model_name="customvariable",
            name="value",
            field=models.JSONField(),
        ),
    ]
