# Generated by Django 6.0.7 on 2026-08-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_customvariable_typed_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmproviderconfig',
            name='context_window_tokens',
            field=models.PositiveIntegerField(default=32768),
        ),
        migrations.AddField(
            model_name='llmproviderconfig',
            name='max_output_tokens',
            field=models.PositiveIntegerField(default=4096),
        ),
        migrations.AddField(
            model_name='llmproviderconfig',
            name='max_retries',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='llmproviderconfig',
            name='request_timeout_seconds',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='llmproviderconfig',
            name='supports_json_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llmproviderconfig',
            name='supports_tool_calling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='anonymization_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='anonymization_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
