# Generated by Django 6.0.7 on 2026-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_llmproviderconfig_context_window_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdrTrellixConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('iam_token_url', models.URLField(blank=True, default='', max_length=500)),
                ('api_base_url', models.URLField(blank=True, default='', max_length=500)),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_secret', models.TextField(blank=True, default='')),
                ('tenant_id', models.CharField(blank=True, default='', max_length=255)),
                ('read_scopes', models.JSONField(blank=True, default=list)),
                ('action_scopes', models.JSONField(blank=True, default=list)),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=120)),
                ('max_rows', models.PositiveIntegerField(default=1000)),
                ('max_window_hours', models.PositiveIntegerField(default=24)),
                ('allow_containment', models.BooleanField(default=False)),
                ('poll_enabled', models.BooleanField(default=False)),
                ('poll_interval_seconds', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_edr_trellix_config',
            },
        ),
        migrations.CreateModel(
            name='SiemQRadarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('base_url', models.URLField(blank=True, default='', max_length=500)),
                ('api_token', models.TextField(blank=True, default='')),
                ('api_version', models.CharField(blank=True, default='22.0', max_length=20)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('ca_bundle_path', models.CharField(blank=True, default='', max_length=500)),
                ('search_timeout_seconds', models.PositiveIntegerField(default=300)),
                ('metadata_timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_rows', models.PositiveIntegerField(default=1000)),
                ('default_window_minutes', models.PositiveIntegerField(default=60)),
                ('max_window_hours', models.PositiveIntegerField(default=24)),
                ('max_concurrent_searches', models.PositiveSmallIntegerField(default=2)),
                ('allow_write', models.BooleanField(default=False)),
                ('poll_enabled', models.BooleanField(default=False)),
                ('poll_interval_seconds', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_siem_qradar_config',
            },
        ),
    ]
