# Generated by Django 6.0.7 on 2026-08-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_edrtrellixconfig_siemqradarconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('bot_token', models.TextField(blank=True, default='')),
                ('asp_base_url', models.URLField(blank=True, default='', max_length=500)),
                ('retry_limit', models.PositiveSmallIntegerField(default=3)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=20)),
                ('aggregation_window_seconds', models.PositiveIntegerField(default=300)),
                ('aggregation_threshold', models.PositiveIntegerField(default=3)),
                ('quiet_hours_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quiet_hours_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_telegram_notification_config',
            },
        ),
    ]
