# Generated by Django 6.0.7 on 2026-08-17 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_telegramnotificationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='IocVerificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('internal_sources_only', models.BooleanField(default=False, help_text='Skip web MCP lookups entirely and rely on OTX/OpenCTI.')),
                ('reputable_domains', models.JSONField(blank=True, default=list)),
                ('internal_networks', models.JSONField(blank=True, default=list)),
                ('internal_domains', models.JSONField(blank=True, default=list)),
                ('max_web_results', models.PositiveIntegerField(default=8)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=30)),
                ('ttl_ip_hours', models.PositiveIntegerField(default=24)),
                ('ttl_domain_hours', models.PositiveIntegerField(default=72)),
                ('ttl_url_hours', models.PositiveIntegerField(default=72)),
                ('ttl_hash_hours', models.PositiveIntegerField(default=720)),
                ('ttl_email_hours', models.PositiveIntegerField(default=168)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_ioc_verification_config',
            },
        ),
        migrations.CreateModel(
            name='McpServerConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('transport', models.CharField(choices=[('http', 'Streamable HTTP'), ('stdio', 'stdio')], default='http', max_length=10)),
                ('url_or_command', models.CharField(blank=True, default='', max_length=1000)),
                ('auth_header', models.CharField(blank=True, default='', max_length=100)),
                ('token', models.TextField(blank=True, default='')),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('allowed_tools', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_mcp_servers',
                'ordering': ['name'],
            },
        ),
    ]
