# Generated by Django 6.0.7 on 2026-08-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_iocverificationconfig_mcpserverconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='edrtrellixconfig',
            name='ingest_lookback_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='edrtrellixconfig',
            name='threat_score_min',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='edrtrellixconfig',
            name='threat_severities',
            field=models.JSONField(blank=True, default=list, help_text='Trellix severity codes to ingest. Empty means s3, s4 and s5.'),
        ),
    ]
