# Generated by Django 6.0.7 on 2026-08-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_edrtrellixconfig_ingest_lookback_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimeconfig',
            name='asset_naming_rules',
            field=models.JSONField(blank=True, default=list, help_text='Ordered fallback rules mapping a hostname pattern to a device type, e.g. [{"pattern": "^SRV-", "device_type": "server", "owner": "Infra"}].'),
        ),
    ]
