# Generated by Django 6.0.7 on 2026-08-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_runtimeconfig_asset_naming_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimeconfig',
            name='correlation_window_hours',
            field=models.PositiveIntegerField(default=24, help_text='An alert joins an open Case with the same correlation key when that Case was active within this many hours.'),
        ),
    ]
