# Generated by Django 6.0.7 on 2026-08-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_runtimeconfig_correlation_window_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('product_name', models.CharField(default='SOC Platform', max_length=120)),
                ('product_short_name', models.CharField(default='SOC', max_length=40)),
                ('logo_full', models.FileField(blank=True, null=True, upload_to='branding/')),
                ('logo_compact', models.FileField(blank=True, null=True, upload_to='branding/')),
                ('logo_mark', models.FileField(blank=True, null=True, upload_to='branding/')),
                ('logo_dark', models.FileField(blank=True, help_text='Light-text variant for dark surfaces such as the sidebar.', null=True, upload_to='branding/')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='branding/')),
                ('login_background', models.FileField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#1677ff', max_length=9)),
                ('accent_color', models.CharField(default='#1677ff', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_branding_config',
            },
        ),
    ]
