# Generated by Django 6.0.7 on 2026-08-18 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_brandingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybookAutomationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('max_auto_runs_per_case', models.PositiveIntegerField(default=3, help_text='Trần số playbook tự chạy cho một case (ceiling of auto-started playbooks per case)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_playbook_automation_config',
            },
        ),
        migrations.CreateModel(
            name='PlaybookAutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Chuỗi con khớp không phân biệt hoa thường trên title + rule name (case-insensitive substrings)')),
                ('min_severity', models.CharField(blank=True, choices=[('', 'Any'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='', max_length=20)),
                ('playbook_name', models.CharField(help_text='NAME của playbook sẽ chạy (playbook NAME to launch)', max_length=255)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_playbook_automation_rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelVirusTotalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('api_keys', models.JSONField(blank=True, default=list, help_text='Danh sách API key, xoay vòng theo từng request (list of API keys rotated per request)')),
                ('base_url', models.URLField(default='https://www.virustotal.com/api/v3', max_length=500)),
                ('proxy', models.CharField(blank=True, default='', max_length=500)),
                ('timeout_seconds', models.PositiveIntegerField(default=20)),
                ('requests_per_minute_per_key', models.PositiveIntegerField(default=4, help_text='Trần request/phút cho mỗi key (per-key request ceiling, VT free tier = 4)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_ti_virustotal_config',
            },
        ),
    ]
