# Generated by Django 6.0.7 on 2026-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_playbookautomationconfig_playbookautomationrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookautomationrule',
            name='fallback',
            field=models.BooleanField(default=False, help_text='Chỉ chạy khi chưa có playbook nào khác trên case (runs only when no other playbook exists on the case)'),
        ),
    ]
