# Generated by Django 6.0.7 on 2026-08-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_playbookautomationrule_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmproviderconfig',
            name='fallback_models',
            field=models.JSONField(blank=True, default=list, help_text='Các model dự phòng thử lần lượt khi model chính lỗi/hết quota (fallback models tried in order when the primary fails)'),
        ),
    ]
