# Generated by Django 6.0.7 on 2026-08-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_llmproviderconfig_fallback_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationClusteringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('window_hours', models.PositiveIntegerField(default=24, help_text='Length of the sliding window the worker clusters over. SHB shift pattern decides this value (S4 open question 3).')),
                ('link_threshold', models.FloatField(default=0.5, help_text='Minimum edge score for membership, between 0 and 1.')),
                ('min_shared_entities', models.PositiveSmallIntegerField(default=1, help_text='Entities two records must share before an edge is scored at all.')),
                ('max_cases_per_run', models.PositiveIntegerField(default=500, help_text='Ceiling on records pulled into one clustering pass, so a backlog cannot stall the worker.')),
                ('poll_interval_seconds', models.PositiveIntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_correlation_clustering_config',
            },
        ),
        migrations.CreateModel(
            name='ThreatHuntingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('allow_auto_mode', models.BooleanField(default=False, help_text='Master switch for executing hunt queries. While off, every plan stays advisory no matter what is requested (S4 open question 2).')),
                ('default_mode', models.CharField(choices=[('advisory', 'Advisory'), ('auto', 'Auto')], default='advisory', max_length=20)),
                ('max_queries_per_plan', models.PositiveIntegerField(default=12)),
                ('max_plans_per_hour', models.PositiveIntegerField(default=6)),
                ('max_window_hours', models.PositiveIntegerField(default=24, help_text='Time-range ceiling forced onto every generated query.')),
                ('max_rows', models.PositiveIntegerField(default=200, help_text='Row ceiling forced onto every generated query.')),
                ('max_tokens_per_plan', models.PositiveIntegerField(default=60000)),
                ('max_concurrent_searches', models.PositiveSmallIntegerField(default=1, help_text='Concurrent SIEM searches allowed across all running plans (S4 open question 1, shared with S1).')),
                ('max_iterations', models.PositiveSmallIntegerField(default=2, help_text='How many times results may go back to the model for a conclusion.')),
                ('sample_row_limit', models.PositiveSmallIntegerField(default=10, help_text='Rows stored on a query for display, after secret scrubbing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'setting_threat_hunting_config',
            },
        ),
    ]
