# Generated by Django 6.0.7 on 2026-08-19 13:03

import apps.settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_correlationclusteringconfig_threathuntingconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edrtrellixconfig',
            name='action_scopes',
            field=models.JSONField(blank=True, default=apps.settings.models.default_trellix_action_scopes),
        ),
        migrations.AlterField(
            model_name='edrtrellixconfig',
            name='read_scopes',
            field=models.JSONField(blank=True, default=apps.settings.models.default_trellix_read_scopes),
        ),
    ]
