# Generated by Django 6.0.7 on 2026-08-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_alter_edrtrellixconfig_action_scopes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edrtrellixconfig',
            name='platform_api_key',
            field=models.TextField(blank=True, default='', help_text='x-api-key for the /edr/v2 platform API. The OAuth bearer token alone is refused with HTTP 403; alerts, real-time search and historical search all require this key.'),
        ),
        migrations.AddField(
            model_name='edrtrellixconfig',
            name='platform_gateway_url',
            field=models.URLField(blank=True, default='', help_text='Gateway for the /edr/v2 platform API, from the Trellix onboarding email, for example https://api.manage.trellix.com. Separate from api_base_url, which serves the legacy /ft/api endpoints.', max_length=500),
        ),
    ]
